#!/usr/bin/python
#
# Author: Huanglin "Lincoln" Xiong
# Email: hxiong@wpi.edu
# Version: Sep 2014
#
# 

import sys, optparse
from lib.History import History

def main():
    h = History('REPORT_LAST')
    p = optparse.OptionParser(description='Report the results of last time' 
        'harness execution(actually current...?).')
    p.add_option('-V', '--verbose', action='store_true', dest='verbose', \
            help='turn on the verbose output')
    options, arguments = p.parse_args()
    h.report(options.verbose)

if __name__ == '__main__':
    main()
