#!/usr/bin/python
#
# Author: Huanglin "Lincoln" Xiong
# Email: hxiong@wpi.edu
# Version: Sep 2014
#

"""
Add tags for test file(s).
Usage:
    harness-test-add-tags [-R] <test> [-t] <tags>
"""

import sys, os

regex_flag = False
tag_flag = False
test_list = []
tag_list = []
f = open(os.getcwd() + ".test_tag", 'r+')
test_dir = os.getcwd() + "/test/"
def main():
    for arg in sys.argv:
        if '--help' == arg:
            print __doc__
            quit()
        if '-R' == arg:
            regex_flag = True
            continue
        if '-t' == arg:
            tag_flag = True
            continue
        if regex_flag:
            # TODO: Tweak this regex functional
            for d in os.listdir(test_dir):
                for f in os.listdir(test_dir + d):
                    if arg in f:
                        test_list.append(f)
        else:
            for d in os.listdir(test_dir):
                if arg in os.listdir(test_dir + d):
                    test_list.append(arg)
        regex_flag = False
        if tag_flag:
            tag_list.append(arg)
    # write the test_file and tags into .test_tag
    #for test in test_list:
        
if __name__ == '__main__':
    main()
