#!/usr/bin/python
#
# Author: Huanglin "Lincoln" Xiong
# Email: hxiong@wpi.edu
# Version: Sep 2014
#
import os, optparse, re
from lib.History import History

h = History('REPORT_TEST')
test_list = []

def report_test(file_name, optparser, regex=False):
    global test_list
    for d in os.listdir("./test/"):
        if regex:
            try:
                r = re.compile(file_name)
            except:
                optparser.error("Incorrect regular expression taken!")
            for f in os.listdir("./test/" + d):
                if r.match(f):
                    if f not in test_list:
                        test_list.append(f)
        else:
            if file_name in os.listdir("./test/" + d):
                if file_name not in test_list:
                    test_list.append(file_name)

def main():
    global test_list
    p = optparse.OptionParser(description='Report on history of a specific test or'
            'a set of test.')
    p.add_option('-R', dest='regex', \
            help="allow and take one following regular expression")
    options, arguments = p.parse_args()
    if options.regex:
        report_test(options.regex, p, True)
    for arg in arguments:
        report_test(arg, p)
    for test in test_list:
        h.report_test(test)

if __name__ == '__main__':
    main()
