#!/usr/bin/python
#
# Author: Huanglin "Lincoln" Xiong
# Email: hxiong@wpi.edu
# Version: Sep 2014
#

import os, optparse
from lib.History import History
from lib import Harness

test_dir = "./test/new/"
def main():
    Harness.initRunAllTest(os.getcwd())
    # History logging here
    h = History("RUN_ALL")
    h.log("Run all the test.")
    p = optparse.OptionParser(description='Run all test under test/new/.' 
        ' Record result in results/. Put all runned test files to test/unclassified/.')
    options, arguments = p.parse_args()
    if os.listdir(test_dir) == []:
        print "===== No test can be run ======"
        return
    for f in os.listdir(test_dir):
        print "===== Run test: {0} ======".format(f)
        h.log("TEST RUN \"{0}\"".format(f))
        Harness.run_test(f, h.getCounter(), os.getcwd())
    
if __name__ == '__main__':
    main()
