#!/usr/bin/python
#
# Author: Huanglin "Lincoln" Xiong
# Email: hxiong@wpi.edu
# Version: Sep 2014
#

import os, re, optparse
from lib.History import History

test_dir = "./test/"

def print_test(file_name):
    f = open(file_name, 'r')
    print file_name + ":"
    for line in f:
        print line,

def find_test(file_name, optparser, regex=False):
    for d in os.listdir(test_dir):
        cur_dir = test_dir + "/" + d + "/"
        if regex:
            try:
                r = re.compile(file_name)
            except:
                optparser.error("Incorrect regular expression taken!")
            for f in os.listdir(cur_dir):
                if r.match(f):
                    print_test(cur_dir + f)
        else:
            if file_name in os.listdir(cur_dir):
                print_test(cur_dir + file_name)
 
def main():
    p = optparse.OptionParser(description='Print out a specific test for showing')
    p.add_option('-R', dest='regex', \
            help='allow and take one following regular expression')
    options, arguments = p.parse_args()
    if options.regex:
        find_test(options.regex, p, True)
    for arg in arguments:
        find_test(arg, p)

if __name__ == '__main__':
    main()
