#!/usr/bin/python
#
# Author: Huanglin "Lincoln" Xiong
# Email: hxiong@wpi.edu
# Version: Sep 2014
#

"""
Classify test files from test/unclassified/ to test/passed/ or test/failed/.
Usage:
    harness-classify-test [-p][-f][-R][-ALL]
    @param[-p]      Classify the following test files to passed.
    @param[-f]      Classify the following test files to failed.
    @param[-R]      Allow 'regular' expression. Actually this works as if naming
                    'has' the matching pattern.
    @param[-ALL]    Classify all test files to passed or failed.
Example:
    $ harness-classify-test -p -ALL
    Put all test files to pass.
    $ harness-classify-test -f test_unit_isTriangle
    Put test file named "test_unit_isTriangle" to failed.
    $ harness-classify-test -p -R test_unit_
    Put all test files naming match 'test_unit_' to passed.
"""

import os, subprocess, sys, optparse
from lib.History import History

h = History('CLASSIFY')
test_dir = "./test/unclassified/"
test_pass_dir = "./test/passed/"
test_fail_dir = "./test/failed/"
result_dir = "./results/unclassified/"
result_pass_dir = "./results/passed/"
result_fail_dir = "./results/failed/"

pass_flag = False
fail_flag = False
regex_flag = False
all_flag = False
 
def take_arg(arg):
    global pass_flag, fail_flag, regex_flag, all_flag
    if arg == '--help':
        print __doc__
        quit()
    if arg == '-p':
        pass_flag = True
        fail_flag = False
        regex_flag = False
        return
    if arg == '-f':
        fail_flag = True
        pass_flag = False
        regex_flag = False
        return
    if arg == '-R':
        regex_flag = True
        return
    if arg == '-ALL':
        for f in os.listdir(test_dir):
            classify(f)
        return
    if regex_flag == True:
        # TODO: tweak this regex functional
        for f in os.listdir(test_dir):
            if arg in f:
                classify(f)
        regex_flag = False
    else:
        if arg in os.listdir(test_dir):
            classify(arg)

def classify(file_name):
    global pass_flag, fail_flag, regex_flag, all_flag
    if pass_flag == True:
        subprocess.call(["mv", test_dir + file_name, test_pass_dir])
        subprocess.call(["mv", result_dir + file_name + "_{0:04d}".format(h.getCounter()),\
                result_pass_dir])
        h.log("TEST PASS: \"{0}\"".format(file_name))
    elif fail_flag == True:
        subprocess.call(["mv", test_dir + file_name, test_fail_dir])
        subprocess.call(["mv", result_dir + file_name + "_{0:04d}".format(h.getCounter()),\
                result_fail_dir])
        h.log("TEST FAIL: \"{0}\"".format(file_name))
    else:
        print "ERROR: invalid operation taken! This might be caused by bringing \
                in wrong arguments to the command."

def main():
    p = optparse.OptionParser(description='')
    #options, arguments = p.parse_args()
    for arg in sys.argv:
        take_arg(arg)

if __name__ == '__main__':
    main()
