#!/usr/bin/python
#
# Author: Huanglin "Lincoln" Xiong
# Email: hxiong@wpi.edu
# Version: Sep 2014
#

"""
Report the results of last time harness execution(actually current...?).
Usage:
    harness-report-last [-V]
    @param[-V]      Turn on the verbose output
"""

import sys
from lib.History import History

h = History('REPORT_LAST')
verbose = False
if '-V' in sys.argv:
    verbose = True
h.report(verbose)

