#!/usr/bin/python
#
# Author: Huanglin "Lincoln" Xiong
# Email: hxiong@wpi.edu
# Version: Sep 2014
#

import sys, optparse
from lib.History import History

def main():
    p = optparse.OptionParser(description='Report all test runs that have'
            ' been run since the initialization, or reinitialization, of'
            ' the harness.')
    options, arguments = p.parse_args()
    h = History('REPORT_ALL')
    h.report(True)

if __name__ == '__main__':
    main()
